#!/bin/bash

cd k2c16/k2fits/

wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c16/200200000/00000/ktwo200200727-c16_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c16/200200000/00000/ktwo200200728-c16_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c16/211600000/58000/ktwo211658473-c16_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c16/212100000/78000/ktwo212178066-c16_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c16/212200000/05000/ktwo212205146-c16_llc.fits

