#!/bin/bash

#blabla

cd k2fits/

wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c14/248500000/05000/ktwo248505415-c14_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c14/248500000/14000/ktwo248514180-c14_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c14/248500000/93000/ktwo248593082-c14_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c14/248700000/78000/ktwo248778179-c14_llc.fits
wget -q -nH --cut-dirs=6 -r -l0 -c -N -np -R 'index*' -erobots=off http://archive.stsci.edu/pub/k2/lightcurves/c14/248800000/42000/ktwo248842300-c14_llc.fits

